version: '3.5'

services:
  mysql-db:
    container_name: mysql_bd
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --general_log=ON --bind_address=0.0.0.0
    environment:
      MYSQL_DB: 'my_db'
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - mysql
    # build: ./database
networks:
    mysql:
        driver: bridge
volumes:
   my_db: